apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: three-tier
  name: frontend
  labels:
    role: frontend
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        image: 577638370031.dkr.ecr.us-east-1.amazonaws.com/frontend:2
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://amanpathakdevops.study/api/tasks"
        ports:
        - containerPort: 3000
