services:
  backend:
    build: ./mern/backend
    ports: 
      - "5050:5050"
    networks:
      - mern-stack 
    depends_on:
      - mongodb

  frontend:
    build: ./mern/frontend
    ports: 
      - "5173:5173"
    networks:
      - mern-stack
  
  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - mern-stack
    volumes:
      - mongo-data:/data/db 

networks:
  mern-stack:
    driver: bridge 

volumes:
  mongo-data:
    driver: local 